POST http://localhost:8000/api/confirm HTTP/1.1
content-type: application/json

{
    "userType": "admin",
    "school": "LancerHacks",
    "email": "foo@gmail.com",
    "password": "1234thisissecure"
}